### ISSUE TITLE
epoch, step, pse setting

### ISSUE THREAD

**Issue by 1900zyh** [JiahuiYu/neuralgym#3]
Hi Jiahui,

Thanks for your toolkit, it's really helpful !

In my world, an epoch means running through the training dataset once. 
So I'm not sure why you set an epoch as TRAIN_SPE steps ignoring the size of training dataset. 

see [progress_logger](https://github.com/JiahuiYu/neuralgym/blob/master/neuralgym/train/trainer.py#L171)

**Comment by JiahuiYu** [comment]
Hi it is a good question. You are right, basically one epoch means running through the training dataset once. However in some cases, like if you sample a small patch in an image (for tasks like inpainting, super-resolution, etc.), you don't know how to measure one epoch. Also sometimes you just want to save the model frequently (like for every 0.5 epoch), it is better to define an epoch as how many steps to run as a whole unit.

Thus I use `SPE` as `steps per epoch` so that you can define how many iterations you want as a running unit. Just some preferences in developing.

Again, you are right. An epoch means running through the training dataset once.

**Comment by 1900zyh** [comment]
@JiahuiYu Thank you for your fast reply very much!

**Comment by muaxiu** [comment]
Does this mean that the train always covers all train dataset? Just like this:
![3209A94E-828E-4D77-A5C4-D7FF98DE2A4E](https://user-images.githubusercontent.com/24777765/63255261-ef33ff00-c2a7-11e9-833d-da9f3edfdff4.png)

**Comment by JiahuiYu** [comment]
Yes, it is also possible that one SPE is larger than the length of train dataset.

**Comment by muaxiu** [comment]
> Yes, it is also possible that one SPE is larger than the length of train dataset.

Thank you very much!
